#!/bin/bash
# mettre le nom du film a creer en argument 1

if [ $# -ne 1 ]; then                                         #Test si on a bien 2 args
	echo "mettre uniquement le nom du .avi a créer"
else
	mencoder mf://*.png -mf w=640:h=480:fps=25:type=png -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell -oac copy -o "$1".avi
fi


